/**
 * Exception type module
 *
 * @packageDocumentation
 */

export const enum ExceptionType {
	GENERAL = 'GENERAL',
	NOT_FOUND = 'NOTFOUND',
	AUTH_NOT_FOUND = 'AUTH_NOTFOUND',
	INVALID_ATOM = 'INVALID_ATOM',
	UNAUTHORIZED = 'UNAUTHORIZED',
	INVALID_REQUEST = 'INVALID_REQUEST',
	AUTH_INVALID_PASSWORD = 'AUTH_INVALID_PASSWORD'
}
